version: "3.9"

services:
  toyota-data-feeder:
    image: aleyasiddika/toyota_data_feeder:1.0
    container_name: toyota-data-feeder
    environment:
      - MQTT_URL=mosquitto
      - MQTT_PORT=8883
      - CLIENT_ID=student2307277-client
    depends_on:
      - mosquitto
    networks:
      - student2307277-net

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1884:1883"
      - "8883:8883"
    volumes:
      - "./mosquitto/conf:/mosquitto/config"
      - "./mosquitto/certs:/mosquitto/certs"
    networks:
      - student2307277-net

networks:
  student2307277-net:
    driver: bridge
